# Generated by Django 3.1.2 on 2020-10-12 12:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('text', models.TextField(max_length=600)),
                ('date', models.DateTimeField(default=datetime.datetime.today)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subject', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(default='', max_length=50)),
                ('text', models.TextField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('availability', models.CharField(choices=[('for sale', 'for sale'), ('sold out', 'sold out')], default='', max_length=50)),
                ('location', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(null=True, upload_to='property/')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('image', models.ImageField(null=True, upload_to='property/')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('video', models.FileField(null=True, upload_to='property/')),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('total_plots', models.CharField(default='', max_length=50)),
                ('plots_sold_out', models.CharField(default='', max_length=50)),
                ('plots_available', models.CharField(default='', max_length=50)),
                ('total_area', models.CharField(default='', max_length=50)),
                ('open_space', models.CharField(default='', max_length=50)),
                ('utility', models.CharField(default='', max_length=50)),
                ('amenities', models.CharField(default='', max_length=50)),
                ('roads', models.CharField(default='', max_length=50)),
                ('plotted', models.CharField(default='', max_length=50)),
                ('mortgage', models.CharField(default='', max_length=50)),
                ('characteristics', models.TextField(default='', max_length=65535)),
                ('speciality', models.TextField(default='', max_length=65535)),
                ('image', models.ImageField(null=True, upload_to='property')),
                ('properties', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='venture.property')),
            ],
        ),
    ]
